project: "Death3DCNN"
experiment_name: "exp1"
hypothesis: "-"

# Model params
in_channels: 1
out_channels_conv1: 16
out_channels_conv2: 32
out_channels_conv3: 64
output_dim_target: 50
kernel_conv: 3
kernel_pool: 2
dropout: 0.5

# training params

gamma: 0.1
# Data paths
scans_path: "/data/..."
clinical_vars_path: "/data/NSCLC-Radiomics-Lung1.clinical-version3-Oct-2019.csv"

# Directory for saving results
work_dir: "." # stick to absolute paths
results_dir: "./results"