project: "Death3DCNN"
experiment_name: "exp1"
hypothesis: "-"

# Model params
in_channels: 1
out_channels_conv1: 16
out_channels_conv2: 32
out_channels_conv3: 64
output_dim_target: 50
kernel_conv: 3
kernel_pool: 2
dropout: 0.5

# training params
num_epochs: 100
batch_size: 1
lr: 0.001
gamma: 0.1
# Data paths
scans_path_train: "/Users/VictoriaShevchenko/Documents/biohack/data/train"
scans_path_test: "/Users/VictoriaShevchenko/Documents/biohack/data/test"
clinical_vars_path: "/Users/VictoriaShevchenko/Documents/biohack/data/NSCLC-Radiomics-Lung1.clinical-version3-Oct-2019.csv"

# Directory for saving results
work_dir: "." # stick to absolute paths
results_dir: "./results"